### ISSUE TITLE
Failed to read character file due to "Unknown facial hair count"

### ISSUE THREAD

**Issue by tjensen** [diogotr7/starchar#1]
Trying to load my character into the app: [Clown1.zip](https://github.com/diogotr7/starchar/files/15286378/Clown1.zip) (zipped because GitHub blocks attaching the .chf file)

Results in an error:
![image](https://github.com/diogotr7/starchar/assets/798166/745084dc-1313-4ab0-ad5d-f6dc1361ce33)

With the following logged to the console:
```
index-DVynFsYq.js:51 Failed to read character Error: Unknown facial hair count
    at vL (index-DVynFsYq.js:63:1108595)
    at IK (index-DVynFsYq.js:63:1112415)
    at BK (index-DVynFsYq.js:63:1112867)
    at HK (index-DVynFsYq.js:63:1126969)
    at index-DVynFsYq.js:63:1136997
```

**Comment by diogotr7** [comment]
Hey, thanks for the report!

The error happens because this value is `4` in your file:
https://github.com/diogotr7/starchar/blob/a7b45bcf05c67a0a70ef67d4d0ffcd03c3f0120c/src/Chf/FacialHair.ts#L85-L95


Adjusting the code to also accept the value `4` seems to work, but i'm not sure if this will break anything else in the future. I'll push a fix with it anyway and we'll see what happens :)
